server:
  port: 8000
spring:
  h2:
    console:
      enabled: true
      path: /h2/database
  liquibase:
    change-log: classpath:db.changelog/changelog.yml
    enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/testdb;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
