ALTER SEQUENCE profiles_seq RESTART WITH 8;
ALTER SEQUENCE profiles_seq INCREMENT BY 1;

ALTER SEQUENCE quotes_seq RESTART WITH 8;
ALTER SEQUENCE quotes_seq INCREMENT BY 1;

ALTER SEQUENCE votes_seq RESTART WITH 8;
ALTER SEQUENCE votes_seq INCREMENT BY 1;

drop sequence profiles_seq;